plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
}

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

minecraft {
    runs.register("client")
    runs.register("server")
    runs.register("data")
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    mavenLocal()
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven {
        url = uri("https://maven.terraformersmc.com/")
    }
}

minecraft.mavenizer(repositories)


dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    // JEI
    if (RUN_JEI == "true") {
        runtimeOnly("mezz.jei:jei-${minecraft_version}-forge:$jei_version")
    }

    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}