plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '7.0.0-beta.6'
}

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs.register("client")
    runs.register("server")
    runs.register("data")
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    mavenLocal()
    maven minecraft.maven
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven {
        url = uri("https://maven.terraformersmc.com/")
    }
}


dependencies {
    implementation minecraft.dep("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    // JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:$jei_version")
    if (RUN_JEI == "true") {
        //runtimeOnly("mezz.jei:jei-${minecraft_version}-forge:$jei_version")
    }

    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}